In [1]:
import pandas as pd

In [4]:
data = pd.read_csv('house_price_regression_dataset.csv')

In [6]:
data

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360,2,1,1981,0.599637,0,5,2.623829e+05
1,4272,3,3,2016,4.753014,1,6,9.852609e+05
2,3592,1,2,2016,3.634823,0,9,7.779774e+05
3,966,1,2,1977,2.730667,1,8,2.296989e+05
4,4926,2,1,1993,4.699073,0,8,1.041741e+06
...,...,...,...,...,...,...,...,...
995,3261,4,1,1978,2.165110,2,10,7.014940e+05
996,3179,1,2,1999,2.977123,1,10,6.837232e+05
997,2606,4,2,1962,4.055067,0,2,5.720240e+05
998,4723,5,2,1950,1.930921,0,7,9.648653e+05
999,3268,4,2,1983,3.108790,2,2,7.425993e+05

In [8]:
data.isna().sum()

Square_Footage          0
Num_Bedrooms            0
Num_Bathrooms           0
Year_Built              0
Lot_Size                0
Garage_Size             0
Neighborhood_Quality    0
House_Price             0
dtype: int64

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Square_Footage        1000 non-null   int64
 1   Num_Bedrooms          1000 non-null   int64
 2   Num_Bathrooms         1000 non-null   int64
 3   Year_Built            1000 non-null   int64
 4   Lot_Size              1000 non-null   float64
 5   Garage_Size           1000 non-null   int64
 6   Neighborhood_Quality  1000 non-null   int64
 7   House_Price           1000 non-null   float64
dtypes: float64(2), int64(6)
memory usage: 62.6 KB

In [14]:
data

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360,2,1,1981,0.599637,0,5,2.623829e+05
1,4272,3,3,2016,4.753014,1,6,9.852609e+05
2,3592,1,2,2016,3.634823,0,9,7.779774e+05
3,966,1,2,1977,2.730667,1,8,2.296989e+05
4,4926,2,1,1993,4.699073,0,8,1.041741e+06
...,...,...,...,...,...,...,...,...
995,3261,4,1,1978,2.165110,2,10,7.014940e+05
996,3179,1,2,1999,2.977123,1,10,6.837232e+05
997,2606,4,2,1962,4.055067,0,2,5.720240e+05
998,4723,5,2,1950,1.930921,0,7,9.648653e+05
999,3268,4,2,1983,3.108790,2,2,7.425993e+05

In [16]:
X = data.drop(['House_Price'],axis = 1,inplace = False)
y = data['House_Price']

In [20]:
X

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality
0,1360,2,1,1981,0.599637,0,5
1,4272,3,3,2016,4.753014,1,6
2,3592,1,2,2016,3.634823,0,9
3,966,1,2,1977,2.730667,1,8
4,4926,2,1,1993,4.699073,0,8
...,...,...,...,...,...,...,...
995,3261,4,1,1978,2.165110,2,10
996,3179,1,2,1999,2.977123,1,10
997,2606,4,2,1962,4.055067,0,2
998,4723,5,2,1950,1.930921,0,7
999,3268,4,2,1983,3.108790,2,2

In [22]:
y

0      2.623829e+05
1      9.852609e+05
2      7.779774e+05
3      2.296989e+05
4      1.041741e+06
           ...
995    7.014940e+05
996    6.837232e+05
997    5.720240e+05
998    9.648653e+05
999    7.425993e+05
Name: House_Price, Length: 1000, dtype: float64

In [24]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=44, shuffle =True)

#Splitted Data

print('X_train shape is ' , X_train.shape)
print('X_test shape is ' , X_test.shape)
print('y_train shape is ' , y_train.shape)
print('y_test shape is ' , y_test.shape)

X_train shape is  (750, 7)
X_test shape is  (250, 7)
y_train shape is  (750,)
y_test shape is  (250,)

In [26]:
X_train.head()

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality
738,1223,2,3,2017,0.727516,2,9
417,3965,1,2,1977,4.983792,0,2
422,4579,2,3,2005,2.595571,0,10
880,3976,5,1,1955,3.903504,0,3
765,2538,4,3,1998,4.892147,0,10

In [32]:
from sklearn.linear_model import LinearRegression

In [36]:
LinearRegressionModel = LinearRegression(fit_intercept=True,copy_X=True,n_jobs=-1)

In [38]:
%%time
LinearRegressionModel.fit(X_train, y_train)

CPU times: total: 46.9 ms
Wall time: 24 ms

LinearRegression(n_jobs=-1)

In [40]:
print('Linear Regression Train Score is : ' , LinearRegressionModel.score(X_train, y_train))

Linear Regression Train Score is :  0.9986135542205642

In [42]:
y_pred = LinearRegressionModel.predict(X_test)

In [44]:
list(y_pred)

[884428.3165933574,
 654265.7676485865,
 693004.0436397241,
 492787.7956093908,
 715223.5351584102,
 233499.6915734997,
 800928.1009672959,
 430199.1508521647,
 278102.9671438481,
 769631.8396192733,
 793535.5888440157,
 349053.8059664434,
 904203.6581699541,
 736942.099249267,
 334088.8370452295,
 678385.3174105375,
 966719.1064618458,
 659712.6691975337,
 1017791.1163404924,
 692268.7964321906,
 433769.2018947187,
 900315.692742527,
 219168.78734048363,
 496721.2761522834,
 845490.0071832784,
 720801.9242233131,
 906366.1280464227,
 673928.9169647321,
 623629.91748528,
 606339.0806958904,
 415002.7381626335,
 536084.0962544242,
 888980.2400334454,
 1005910.6695382665,
 520649.27952882834,
 777408.7028573113,
 573809.3234465583,
 827036.7126769298,
 544356.3579575266,
 646577.2862303536,
 420893.22158433683,
 788395.9336583191,
 366039.80252858205,
 547468.9745079433,
 441222.4597646566,
 380115.5205067387,
 648694.6261657798,
 117762.4035259597,
 848971.6434648852,
 929674.7213280154,
 358817.5663756565,
 404658.70884693554,
 528528.1364241159,
 686143.9108669139,
 539398.7141311737,
 895973.9106331277,
 691247.5748116705,
 241021.58536059503,
 681657.3387519144,
 1023565.3518405231,
 732297.0469695721,
 266983.99725713255,
 324448.5913117118,
 451977.564468944,
 324784.04796835827,
 662377.4286349402,
 306390.10356768826,
 931069.5637357943,
 1010712.3952899901,
 594377.8751982921,
 907045.3299441207,
 575942.8847910608,
 978163.9852544651,
 644237.9045381872,
 993883.1474902076,
 684409.534263493,
 909421.7390722269,
 351763.7939386256,
 302485.6374414582,
 318018.20383286336,
 971870.7028747755,
 820212.8314070273,
 231513.93533483334,
 825536.1698986976,
 663335.9503662596,
 1009363.5875493749,
 868304.2985870214,
 626885.455028832,
 215452.93948843144,
 831057.9258408681,
 1043772.7480022558,
 220021.79658593796,
 759037.3884251541,
 739001.7458122224,
 459579.25167936785,
 884968.802680302,
 174164.13935689023,
 569429.4889267823,
 437498.7917397772,
 785761.6421980993,
 975856.6680062483,
 308510.67417824315,
 663346.4453031807,
 755671.7272465765,
 733093.1952880397,
 1071439.8939042236,
 1040643.6769908178,
 496479.03748965776,
 382927.5560238408,
 728318.3772886484,
 218686.5724653788,
 904729.9744360857,
 1002655.3794067507,
 1034349.65845124,
 708535.1773919924,
 725433.19771535,
 780040.0485220817,
 327254.80229416955,
 795061.1999991206,
 774671.639222946,
 759746.5295322295,
 948364.3950557578,
 877011.6397599424,
 1081750.466982949,
 401565.65152650466,
 449803.93626475055,
 629036.6357895001,
 884700.342740016,
 615922.1998929204,
 656415.7823362625,
 892711.3367968439,
 525540.8419955671,
 623027.2732714158,
 427826.0166561436,
 355848.59550470207,
 613767.4013687172,
 860777.1218751143,
 742561.1277996716,
 548376.9804042922,
 456130.7293396117,
 761707.0877587674,
 403914.3790827007,
 181647.26569121564,
 416102.0420498396,
 774307.6476668557,
 962856.5250049084,
 531835.4802252417,
 535006.92649364,
 753066.5140859573,
 833972.793965566,
 357550.86077440483,
 437361.83163851034,
 909738.2463967456,
 711664.8859259686,
 492690.5312607824,
 818782.9266838836,
 122788.0269696964,
 244102.7504403023,
 1035027.6240824363,
 348273.2079578149,
 818913.0026571727,
 1102834.794108977,
 943833.7549782316,
 713586.4545683484,
 505272.1328310184,
 540563.3376598377,
 524768.1649191999,
 759246.2649969757,
 304228.08135790797,
 164756.9747783714,
 527904.2280942802,
 433057.5470486535,
 995918.2446869416,
 625166.6387349837,
 514831.35449390067,
 372452.339442424,
 512179.4489502255,
 895472.7036373969,
 903695.4139343388,
 819886.1205002144,
 150084.56505553192,
 503096.48750868905,
 651270.8845011895,
 925237.0590627585,
 505863.7721324852,
 681341.9785900027,
 280592.73248049803,
 690078.8407984795,
 531786.249646253,
 515840.7508387645,
 615830.7825076478,
 757136.6782573829,
 198425.25613659434,
 794170.5606808513,
 548923.2158430843,
 940230.9450218086,
 509181.4077646951,
 253401.61354022473,
 344963.51189382235,
 819505.5686104731,
 781348.7145521054,
 259790.15165370703,
 541038.4091752609,
 575911.9777569012,
 597457.9735114225,
 613714.0535157789,
 456295.4202537397,
 825396.2791339019,
 541385.5358607611,
 980163.6826165318,
 329741.52907955553,
 700509.8370453133,
 558694.4406059477,
 969945.0029610307,
 835235.1898446172,
 856424.265676315,
 1026929.4295723503,
 590928.6123400549,
 879226.2490719366,
 589390.1275418298,
 863191.437878056,
 504132.83257136866,
 496942.61149441125,
 696257.1379264905,
 463491.65822335426,
 931127.2733765403,
 316293.20680087013,
 769689.6144664125,
 732462.494014434,
 262978.09763739025,
 291296.8641303391,
 352341.1775495885,
 579592.1017605993,
 857042.5466952887,
 542009.6600100482,
 380641.5474616289,
 904510.6986017874,
 1023691.0662358347,
 384715.66871718643,
 858553.4854473132,
 643955.0548924492,
 135095.8233254673,
 472477.14250826975,
 453686.74002327444,
 160129.26402783394,
 711979.5015491582,
 1055562.1692307033,
 759766.7679127366,
 859141.2315907236,
 987358.1316450876]

In [48]:
list(y_test)

[886568.3132277146,
 672852.0519810001,
 697574.5556670319,
 481489.24616078194,
 728289.8873118911,
 236054.0002831533,
 787281.7359378719,
 424712.5512524801,
 268244.1761186752,
 772740.0707275409,
 799178.3100544005,
 338786.44407016825,
 912468.0479046734,
 749610.4677553453,
 338170.31528112484,
 678385.989963216,
 964865.2986386952,
 639073.1842415399,
 1010183.5001098072,
 694917.3008745462,
 432687.983790756,
 888140.07598706,
 229698.9186636115,
 492018.32279508375,
 826494.0471232897,
 731490.1175330897,
 934942.0571329228,
 665969.5719032948,
 611205.6889207754,
 629609.0984680437,
 397346.1108776756,
 527544.910534171,
 898283.8867356428,
 1021278.340082141,
 517655.1581174146,
 779336.1178319983,
 551668.6465406333,
 838774.4840391098,
 541967.633559251,
 656980.4604282172,
 417416.2622542783,
 780363.0627911759,
 364016.40122898977,
 526951.7757612201,
 443005.62363881344,
 384461.3548261602,
 650748.6977489772,
 113576.5123703764,
 841676.0140843305,
 919295.8540615214,
 359657.9955923103,
 402330.051233892,
 538851.8933945443,
 683723.1607044176,
 551463.8888534079,
 893926.6294720689,
 699683.2484112402,
 251359.7986427481,
 676233.0768279255,
 1033450.4577544982,
 733900.7559066785,
 262382.8522740563,
 318266.2771320871,
 451409.4809711031,
 329218.5249164853,
 660507.8198303543,
 300935.18607341987,
 947490.777477816,
 1004456.2194818492,
 586086.5685389101,
 891638.5086964626,
 583183.4309103092,
 985699.1860734548,
 656065.8419892447,
 985628.9692003924,
 685644.2336178538,
 914555.7450033636,
 338350.5954344411,
 280149.1863612468,
 320689.2188217977,
 971977.0246414564,
 821117.7482116626,
 233504.5137836983,
 823529.5488742903,
 676719.1220590248,
 1000021.7606809204,
 901000.4882338208,
 637736.0103999889,
 198659.21988081493,
 828512.1019589091,
 1046163.3264236908,
 209632.84147750464,
 774150.0468123948,
 740286.5597469498,
 462185.7241886994,
 885550.3826256534,
 158856.84303466187,
 578870.7619594942,
 418888.6616954587,
 786580.3015186453,
 985260.854490162,
 308618.40727220185,
 663904.9927177994,
 750481.7169351575,
 730405.6620242158,
 1075814.4318808403,
 1039730.2135109294,
 504023.26087166165,
 355281.41848528635,
 719969.4352945103,
 217010.48526715024,
 922420.588370604,
 1004325.3931894517,
 1021134.6211894122,
 704212.5239765074,
 734110.0243598827,
 748220.493682927,
 355453.1829292205,
 797034.4255040532,
 779202.6809723858,
 769087.1879559917,
 944921.9815744858,
 883626.6203857235,
 1092026.89678641,
 414166.584309186,
 450941.1354372639,
 625227.045470116,
 894261.7196452515,
 626454.2784147046,
 647832.2075906589,
 897666.0008462978,
 539478.4031506823,
 625113.6084591298,
 431423.2948124018,
 344363.2736819858,
 600207.3340100806,
 875981.0268954616,
 738091.5512277477,
 543160.4942000011,
 453359.87163545546,
 760720.1464642045,
 390430.2223774808,
 199066.37891066872,
 427947.1030973768,
 779362.3561113286,
 967780.6667222162,
 533178.2402465394,
 531945.983279591,
 762769.5055574658,
 834328.5793736472,
 354744.6305953098,
 443408.3059778237,
 903251.9405609448,
 695362.741532193,
 503962.1877251642,
 818706.7764361517,
 120795.5523667112,
 250101.5473305484,
 1037911.6519852468,
 362679.08775021497,
 827140.4447152761,
 1107045.062935083,
 936969.4548360409,
 710065.5617561329,
 507847.5873391124,
 538349.0962151848,
 523323.0670600654,
 753186.167662594,
 319601.3915396029,
 165242.29785174478,
 537770.4956241908,
 441001.3484190839,
 985499.1963159838,
 625246.1179756841,
 507554.9440535184,
 383644.1777444591,
 509725.550655089,
 926488.454118578,
 896792.553841208,
 820831.6964017673,
 158454.83915736206,
 496427.1035646905,
 656223.1627305328,
 933332.7201261588,
 504682.30124801846,
 665309.7683934513,
 294558.07202157495,
 708104.0557380343,
 539133.0843265855,
 518166.38138878136,
 622100.1895022333,
 749471.4241491086,
 191117.1012230497,
 809046.2841762663,
 551444.6316158974,
 935451.9335719376,
 527715.5373919866,
 250123.469112831,
 350816.184399563,
 826606.0146181242,
 793995.2848757812,
 246540.9659359964,
 527393.5128875901,
 572941.4282388942,
 605371.7047170609,
 617900.4948407207,
 450594.5679766036,
 816939.5874308393,
 530824.1967752124,
 996696.835850388,
 325738.14789058163,
 688357.648480334,
 562238.4809757017,
 985223.9966541852,
 842172.2092376931,
 845932.4082879503,
 1019192.6613592046,
 582468.7977365239,
 897176.5668201512,
 601890.2919093702,
 870504.8285910133,
 507967.8360673265,
 497340.9981159924,
 703413.1109446795,
 470978.4795328964,
 926531.8100085806,
 310471.3888855296,
 758293.3788835382,
 740148.1937768575,
 251724.67925135957,
 296291.0010075069,
 347769.0613211003,
 585574.1096146859,
 852599.97505604,
 524818.9633293215,
 373171.5899458196,
 898403.5372117123,
 1046315.8960136625,
 405144.670068021,
 852368.6069601658,
 646118.3979191775,
 147206.86576297088,
 480961.44203831744,
 448879.5107617519,
 146020.40342022013,
 708003.0797050629,
 1058290.680940349,
 738643.2007694525,
 875163.0460692297,
 976572.7481782682]

In [50]:
from sklearn.metrics import mean_squared_error

In [52]:
MSEValue = mean_squared_error(y_test, y_pred, multioutput='uniform_average') # it can be raw_values
print('Mean Squared Error Value is : ', MSEValue)

Mean Squared Error Value is :  109355982.02518395

In [54]:
from sklearn.linear_model import LinearRegression,SGDRegressor,Lasso,Ridge
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor


from sklearn.metrics import mean_absolute_error,mean_squared_error,median_absolute_error 

LinearRegressionModel = LinearRegression(fit_intercept=True, copy_X=True,n_jobs=-1)
SGDRegressionModel = SGDRegressor(alpha=0.1,random_state=33,penalty='l2',loss = 'huber')
LassoRegressionModel = Lasso(alpha=1.0,random_state=33)
RidgeRegressionModel = Ridge(alpha=1.0,random_state=33)
RandomForestRegressorModel = RandomForestRegressor(n_estimators=1000,max_depth=8, random_state=33)
GBRModel = GradientBoostingRegressor(n_estimators=500,max_depth=7,learning_rate = 1.5 ,random_state=33)
SVRModel = SVR(C = 1.0 ,epsilon=0.1,kernel = 'rbf') 
DecisionTreeRegressorModel = DecisionTreeRegressor( max_depth=3,random_state=33)
KNeighborsRegressorModel = KNeighborsRegressor(n_neighbors = 5, weights='uniform',algorithm = 'auto')    


Models = [LinearRegressionModel,SGDRegressionModel,LassoRegressionModel,RidgeRegressionModel,RandomForestRegressorModel,
          GBRModel,SVRModel,DecisionTreeRegressorModel,KNeighborsRegressorModel]





for Model in Models : 
    print(f'for Model {str(Model).split("(")[0]}')
    Model.fit(X_train, y_train)
    y_pred = Model.predict(X_test)
    print(f'MAE value is  : {mean_absolute_error(y_test, y_pred)}')
    print(f'MSE value is  : {mean_squared_error(y_test, y_pred)}')
    print(f'MdSE value is  : {median_absolute_error(y_test, y_pred)}')
    print('=================================================')

for Model LinearRegression
MAE value is  : 8278.08054566303
MSE value is  : 109355982.02518395
MdSE value is  : 7258.478279815317
=================================================
for Model SGDRegressor
MAE value is  : 27806.946264615162
MSE value is  : 1210583706.0624943
MdSE value is  : 23082.91168973621
=================================================
for Model Lasso
MAE value is  : 8278.077978754658
MSE value is  : 109355448.21160364
MdSE value is  : 7259.726501699333
=================================================
for Model Ridge
MAE value is  : 8278.731686164281
MSE value is  : 109360796.67295143
MdSE value is  : 7275.000823736686
=================================================
for Model RandomForestRegressor
MAE value is  : 18079.284539477878
MSE value is  : 544465093.3166617
MdSE value is  : 14917.837745334691
=================================================
for Model GradientBoostingRegressor
MAE value is  : 33044.22740832023
MSE value is  : 1776177719.5564706
MdSE value is  : 26791.998769246362
=================================================
for Model SVR
MAE value is  : 207774.16538523935
MSE value is  : 59937802980.11194
MdSE value is  : 196886.2152533928
=================================================
for Model DecisionTreeRegressor
MAE value is  : 39053.593539165435
MSE value is  : 2308952864.3704667
MdSE value is  : 30708.7692118705
=================================================
for Model KNeighborsRegressor
MAE value is  : 24790.69452924101
MSE value is  : 1005251527.768398
MdSE value is  : 19399.02160391888
=================================================